### PR TITLE
Add notebook code and links

### PR DESCRIPTION
**Pull request by jakubzitny**
Hi @fiftysevendegreesofrad, I saw your piano article on HackerNews and wanted to play around with the code a bit. I thought it would be cool to share the notebook files with you, maybe there would be others that like to play with the code.

PS: I also migrated it to Python 3.

### CODE REVIEW

**Comment by fiftysevendegreesofrad** [comment]
Hi

I tried the deepnote link for the piano notebook and got stuck in an
infinite loop of

Some launch-ception, button below will launch this project

https://deepnote.com/project/278a6f04-3419-4d21-9134-dbfb94ddb59b

I'm happy to merge if that can be fixed?

thank you

**Comment by jakubzitny** [comment]
Oh, I'm sorry I've put the wrong project link to the first button. Fixed now :)

**Comment by fiftysevendegreesofrad** [comment]
Still not fixed I'm afraid - pasting error screen grab below, also the
colab link says 'notebook not found' - I'll paste error text below the
screengrab.

Maybe simplest is if I just move the notebooks over to one of those
services in source form - I only put them on github pages as I wasn't sure
where to host them. Which would you recommend (deepnote vs colab) given my
requirements:
* people should be able to read them without running (I don't mind people
having to login etc if they actually want to run)
* stable provider, I'd like them to still be online in 10 years

I really appreciate you bringing both to my attention, by the way, thank
you :-)

Crispin

Deepnote error:
[image: image.png]
Colab error:
Notebook not found
There was an error loading this notebook. Ensure that the file is
accessible and try again.

Ensure that you have permission to view this notebook in GitHub and
authorize Colaboratory to use the GitHub API.
https://github.com/fiftysevendegreesofrad/JupyterNotes/blob/master/notebook-piano.ipynb

Could not find notebook-piano.ipynb in
https://api.github.com/repos/fiftysevendegreesofrad/JupyterNotes/contents/?per_page=100&ref=master
***@***.***://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20210419-060057-RC00_369185350:87:89
***@***.***://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20210419-060057-RC00_369185350:1388:75
***@***.***://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20210419-060057-RC00_369185350:1378:467
***@***.***://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20210419-060057-RC00_369185350:19:336
***@***.***://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20210419-060057-RC00_369185350:17:503
***@***.***://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20210419-060057-RC00_369185350:20:206
***@***.***://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20210419-060057-RC00_369185350:62:101

**Comment by jakubzitny** [comment]
So, the colab link does not work because this PR is not merged yet. The notebook link is not available in the master branch yet.

And the Deepnote error - I can't see the image, GitHub strips the images from email, can you please paste it here?
https://github.com/fiftysevendegreesofrad/JupyterNotes/pull/1 But both links are openable by anyone without logging in.

Btw, as per your questions, both Colab and Deepnote are about to stay for a while and allow read without running, etc. So that's why I've put the links to both at the beginning. Deepnote has a convenient way of having multiple notebooks in one project so I added both to the same project. (If you create an account, I can invite you to be admin there. Or you can just clone it to have under your account.)

**Comment by fiftysevendegreesofrad** [comment]
Cool, I merged, let's give github pages some time to update and see if it works :)

**Pull request merged**
